name: prjak
channels:
  - defaults
dependencies:
  - python=3.6
  - pip:
    - spacy==2.2.4
    - spacy_cld==0.1.0
    - tqdm==4.46.0
    - pdfminer==20191125
    - pandas==1.0.3
    - numpy==1.18.4
    - geotext==0.4.0
